name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: factorio_verify
            asset_name: factorio_verify-linux
          - os: windows-latest
            artifact_name: factorio_verify.exe
            asset_name: factorio_verify-win

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --features build_z3
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}